### ISSUE TITLE
Correction to docs: i18n tag " incorrect-captcha-sol" seems to be incorrect for the new checkbox Recaptcha...

### ISSUE THREAD

**Issue by valasensio** [ambethia/recaptcha#177]
This tag  `verification_failed`: should replace the ` incorrect-captcha-sol:` tag text within the Recaptcha home page under the i18n section.  This is what worked for me. 

```
en:
  recaptcha:
    errors:
      verification_failed: 'Fail.'
```
